# Copyright (c) 2022, NVIDIA CORPORATION. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
site_name: Triton Model Navigator
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
      primary: black
  features:
    - navigation.top
extra_css:
  - assets/styles.css
repo_url: https://github.com/triton-inference-server/model_navigator
repo_name: Git Repository
plugins:
  - autorefs
  - htmlproofer
  - mike
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_style: google
            show_root_heading: true
            heading_level: 2
            line_length: 120
            docstring_section_style: list
            merge_init_into_class: true
            separate_signature: true
            inherited_members: true
            filters:
            - "!__post_init__"
  - search
watch:
  - model_navigator
  - docs
  - mkdocs.yml
  - LICENSE
  - README.md
  - CHANGELOG.md
  - CONTRIBUTING.md
view_uri_template: blob/{ref}/{path}  # used by scripts/rewrite_links_to_repo.py hook
hooks:
  - scripts/rewrite_links_to_repo.py
extra:
  version:
    provider: mike
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home: README.md
  - Installation: installation.md
  - Quick start: quick_start.md
  - Optimize Model:
    - Using optimize: optimize/optimize.md
    - Optimize API:
      -   Config: optimize/config.md
      -   JAX: optimize/jax.md
      -   ONNX: optimize/onnx.md
      -   TensorFlow 2: optimize/tensorflow.md
      -   TensorRT: optimize/tensorrt.md
      -   PyTorch: optimize/torch.md
      -   Python: optimize/python.md
  - Navigator Package:
    - Using package: package/package.md
    - Package API:
      - Package: package/package_api.md
      - Load: package/package_load_api.md
      - Save: package/package_save_api.md
      - Optimize: package/package_optimize_api.md
      - Profile: package/package_profile_api.md
  - Inference Deployment:
    - PyTriton:
        - Deploying models: pytriton/pytriton_deployment.md
        - PyTritonAdapter API: pytriton/pytriton_adapter.md
    - Triton Inference Server:
        - Deploying models: triton/triton_deployment.md
        - Model Store API:
            - Adding Model: triton/adding_model.md
            - Specialized Configs: triton/specialized_configs.md
            - Instance Group: triton/instance_groups.md
            - Inputs and Outputs: triton/inputs_and_outputs.md
            - Dynamic Batcher: triton/dynamic_batcher.md
            - Sequence Batcher: triton/sequence_batcher.md
            - Accelerators: triton/accelerators.md
            - Model Warmup: triton/warmup.md
  - Examples: examples.md
  - Changelog: CHANGELOG.md
  - Known Issues: known_issues.md
  - Contributing: CONTRIBUTING.md
  - License: LICENSE.md
